version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres_container
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog_api_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:5.5
    container_name: pgadmin4_container
    depends_on:
      - postgres

    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

  blog-api:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog-api
    depends_on:
      - postgres_container
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
